version: '2.1'

services:
  docker-test:
    image: docker-test
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:80
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js